name: 'Build Lambdas and Push to S3'
description: 'Zip up lambdas and lamba layers and push to s3'
inputs:
  bucket:
    description: 'Name of S3 bucket'
    required: true
  role-to-assume:  
    description: 'aws role to assume to push to s3'
    required: true
  region:
    description: 'aws region'
    required: true
  lambda-paths:
    description: `array of relative paths for the lambdas to build and zip`
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
