name: 'Build Lambdas and Push to S3'
description: 'Zip up lambdas and lamba layers and push to s3'
inputs:
  s3-bucket:
    description: 's3 bucket to upload artifacts'
    require: true
  lambda-paths:
    description: |-
      newline-separated list of relative paths for the lambdas to build and zip
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
